---
- hosts: all
  serial: 1

  tasks:
  - name:  Update Apt cache and check that update-notifier-common is installed
    become: True
    apt:  update_cache=yes name=update-notifier-common cache_valid_time=3600

  - name:  Check if there are updates available
    shell: "/usr/lib/update-notifier/apt-check 2>&1 | sed s/\\;//"
    register: hasaptupdates
    ignore_errors: True

  - name: Install required updates 
    become: True
    apt: upgrade=dist 
    when: hasaptupdates.stdout != "00"
